channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.10
  - nvidia::cuda=11.6
  - pytorch::pytorch=1.13
  - pytorch::pytorch-cuda=11.6
  - pytorch::torchvision
  - dglteam::dgl-cuda11.6
  - conda-forge::pytdc
  - conda-forge::rdkit
  - conda-forge::openbabel
  - conda-forge::numpy
  - conda-forge::scipy
  - conda-forge::scikit-learn
  - networkx
  - jupyter
  - matplotlib
  - pandas
  - seaborn
  - tqdm
  - joblib
