channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.9
  - conda-forge::cudatoolkit=11.1
  - pytorch-lts::pytorch=1.8
  - pytorch-lts::torchvision
  - dglteam::dgl-cuda11.1
  - conda-forge::pytdc
  - conda-forge::rdkit
  - conda-forge::openbabel
  - defaults::numpy
  - defaults::scipy
  - defaults::scikit-learn
  - networkx
  - matplotlib
  - pandas
  - seaborn
  - tqdm
  - joblib
