channels:
  - dglteam
  - pytorch-lts
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.8
  - cudatoolkit=11.1
  - dgl-cuda11.1
  - jupyter
  - numpy
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - rdkit
  - openbabel
  - tqdm
  - joblib
