channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- cudatoolkit=11.1
- pytorch-lts::pytorch=1.8
- pytorch-lts::torchvision
- dglteam::dgl-cuda11.1
- jupyter
- numpy
- scipy
- networkx
- scikit-learn
- matplotlib
- pandas
- seaborn
- tqdm
- joblib
- openbabel
